spring:
  application:
    name: yp-mjava-pws-s5-s8

  sql:
    init:
      platform: postgresql
      mode: always

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

#post:
#  shorttext:
#    size: 128

server:
  port: 8085

---

spring:
  config:
    activate:
      on-profile: isolation

  sql:
    init:
      platform: h2

  datasource:
    url: jdbc:h2:mem:usersdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver