spring:
  application:
    name: yp-mjava-pws-s5-s8

  sql:
    init:
      mode: always

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

page:
  layout:
    rowsize: 4

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: isolation

  r2dbc:
    url: r2dbc:h2:mem:///usersdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: